### ISSUE TITLE
setup.py install fails on MacOSX

### ISSUE THREAD

**Issue by philres** [jeffdaily/parasail-python#20]
Hi again,

Thanks for the quick fix! `1.1.10` works now for me on Ubuntu but unfortunately still breaks on macOS Sierra 10.12.6 with the error below if `automake, libtool and autoconf` are not installed.

For me this is not a problem at the moment as `brew install automake libtool autoconf` fixes it. Just wanted to let you know that on a standard Mac parasail won't install at the moment. Unfortunately,  I'm a bit busy right now, but later this week I'm happy to take a look at it myself and see wether I can fix it, in case you don't have time for it.

Thanks,
Philipp

```
(cuecat) prescheneder@preschen-mac ~/Development/PycharmProjects/cuecat $ pip install parasail
Collecting parasail
  Using cached parasail-1.1.10.tar.gz
Requirement already satisfied: numpy in /Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/site-packages (from parasail)
Building wheels for collected packages: parasail
  Running setup.py bdist_wheel for parasail ... error
  Complete output from command /Users/prescheneder/miniconda2/envs/cuecat/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/tmpFutrVOpip-wheel- --python-tag cp27:
  running bdist_wheel
  parasail/libparasail.dylib not found, attempting to build
  Downloading latest parasail master
  Unzipping parasail master archive
  fixing executable bits after unzipping
  Unable to find parasail configure script
  Running autoreconf -fi from ./parasail-master
  GNU M4 1.4.6
  autoconf not found
  automake not found
  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `-' in: --version
  Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
  Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
  CalledProcessError()
  autoreconf not found
  Prepending /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin to PATH
  PATH=/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin:/Users/prescheneder/miniconda2/envs/cuecat/bin:/Users/prescheneder/miniconda2/bin/:/usr/local/bin:/usr/local/sbin:/Users/prescheneder/Development/PycharmProjects/phtools/tools/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/prescheneder/Development/PycharmProjects/phworkspace/tools/
  Building autotools
  Downloading http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
  Expanding m4-1.4.17.tar.gz
  configuring m4
  making and installing m4
  Downloading http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
  Expanding autoconf-2.69.tar.gz
  configuring autoconf
  making and installing autoconf
  Downloading http://ftp.gnu.org/gnu/automake/automake-1.13.4.tar.gz
  Expanding automake-1.13.4.tar.gz
  configuring automake
  making and installing automake
    GEN      automake
    GEN      aclocal
    GEN      t/ax/shell-no-trail-bslash
    GEN      runtest
    GEN      doc/aclocal.1
    GEN      doc/automake.1
    GEN      lib/Automake/Config.pm
    GEN      t/ax/test-defs.sh
    GEN      doc/aclocal-1.13.1
    GEN      doc/automake-1.13.1
  help2man: can't get `--help' info from automake-1.13
  Try `--no-discard-stderr' if option outputs to stderr
  make: *** [doc/automake-1.13.1] Error 255
  make: *** Waiting for unfinished jobs....
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 443, in <module>
      install_requires=INSTALL_REQUIRES,
    File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 405, in run
      prepare_shared_lib()
    File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 399, in prepare_shared_lib
      build_parasail(libname)
    File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 286, in build_parasail
      build_autotools()
    File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 235, in build_autotools
      raise RuntimeError("make of {} failed".format(tool))
  RuntimeError: make of automake failed
  
  ----------------------------------------
  Failed building wheel for parasail
  Running setup.py clean for parasail
Failed to build parasail
Installing collected packages: parasail
  Running setup.py install for parasail ... error
    Complete output from command /Users/prescheneder/miniconda2/envs/cuecat/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-ZdslqC-record/install-record.txt --single-version-externally-managed --compile:
    running install
    parasail/libparasail.dylib not found, attempting to build
    Archive 'parasail-master.zip' already downloaded
    Archive 'parasail-master.zip' already unzipped to /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail
    parasail archive executable permissions ok
    Unable to find parasail configure script
    Running autoreconf -fi from ./parasail-master
    GNU M4 1.4.6
    autoconf not found
    automake not found
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `-' in: --version
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
    CalledProcessError()
    autoreconf not found
    Prepending /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin to PATH
    PATH=/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin:/Users/prescheneder/miniconda2/envs/cuecat/bin:/Users/prescheneder/miniconda2/bin/:/usr/local/bin:/usr/local/sbin:/Users/prescheneder/Development/PycharmProjects/phtools/tools/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/prescheneder/Development/PycharmProjects/phworkspace/tools/
    Building autotools
    m4-1.4.17.tar.gz already exists! Using existing copy.
    m4-1.4.17 already exists! Using existing sources.
    /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin/m4 already exists! Skipping build.
    autoconf-2.69.tar.gz already exists! Using existing copy.
    autoconf-2.69 already exists! Using existing sources.
    /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/autotools/bin/autoconf already exists! Skipping build.
    automake-1.13.4.tar.gz already exists! Using existing copy.
    automake-1.13.4 already exists! Using existing sources.
    configuring automake
    making and installing automake
      GEN      aclocal
      GEN      t/ax/shell-no-trail-bslash
      GEN      automake
      GEN      runtest
      GEN      lib/Automake/Config.pm
      GEN      t/ax/test-defs.sh
      GEN      doc/aclocal-1.13.1
      GEN      doc/automake-1.13.1
    help2man: can't get `--help' info from automake-1.13
    Try `--no-discard-stderr' if option outputs to stderr
    make: *** [doc/automake-1.13.1] Error 255
    make: *** Waiting for unfinished jobs....
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 443, in <module>
        install_requires=INSTALL_REQUIRES,
      File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Users/prescheneder/miniconda2/envs/cuecat/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 416, in run
        prepare_shared_lib()
      File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 399, in prepare_shared_lib
        build_parasail(libname)
      File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 286, in build_parasail
        build_autotools()
      File "/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py", line 235, in build_autotools
        raise RuntimeError("make of {} failed".format(tool))
    RuntimeError: make of automake failed
    
    ----------------------------------------
Command "/Users/prescheneder/miniconda2/envs/cuecat/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-ZdslqC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hx/q0ng7k3n2116hc4k2xhf_zyh3pw2nw/T/pip-build-2tRBtl/parasail/

```

**Comment by jeffdaily** [comment]
Thank you for the bug report.  This was of course the one combination I failed to test before pushing the setup.py changes.  I use homebrew and had the autotools already installed and that was the problem - homebrew perl was not built for threading.  The system's /usr/bin/perl works just fine, so I modified setup.py to prepend /usr/bin to the PATH.

**Comment by philres** [comment]
Well that was quick. Thanks!
