### ISSUE TITLE
Running test suite in travis.

### ISSUE THREAD

**Issue by iiSeymour** [jeffdaily/parasail-python#49]
The test suite needs some work to get up and running again: rough plan -

- [X] Make Python 2 and 3 compatible *(remove use of print statements & pytest)*.
- [X] Use a test framework and test runner *(unittest in the stlib will do the job)*.
- [X] Skip the failing test initially.
- [X] Set `CIBW_TEST_COMMAND` to run the test suite against all the wheels on every commit.
- [ ] Fix the failing tests.
- [ ] Add more tests.

**Comment by iiSeymour** [comment]
@jeffdaily the full test suite is now exercised against all the builds on every commit - see https://travis-ci.org/iiSeymour/parasail-python/ 

Only one test fails *(test_ssw.py)* but I have marked it as expected to fail for know.

```
Done. Your build exited with 0.
.............x.
attempted to set value of built-in matrix 'blosum62'
.Exception ignored in: <function Profile.__del__ at 0x00000219096AAEE8>
Traceback (most recent call last):
  File "C:\Users\travis\AppData\Local\Temp\tmpm67wfjdv\lib\site-packages\parasail\bindings_v2.py", line 547, in __del__
    _lib.parasail_profile_free(self.pointer)
AttributeError: 'Profile' object has no attribute 'pointer'
----------------------------------------------------------------------
Ran 16 tests in 0.013s
```

I also fixed the `sdist` upload and `TWINE_USERNAME` in #50.

**Comment by jeffdaily** [comment]
@iiSeymour I didn't have your email address so reach you directly so using github.  Test suite is merged.  v1.2 is tagged.  Looks like pypi upload worked this time.  Please verify.

**Comment by iiSeymour** [comment]
Much better, you don't need to worry about having `wheel` installed anymore *(to build the wheel after the sdist is downloaded and it saves ~2 minutes at install time)*. Thanks for taking the time to get the release out, I'll update my downstream projects.

```bash
$ pip install parasail==1.1.19 --no-cache                                                                                                                                                                     
Collecting parasail==1.1.19
  Downloading parasail-1.1.19.tar.gz (71 kB)
     |████████████████████████████████| 71 kB 2.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /tmp/p/venv3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-85z4adye/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-85z4adye/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-85z4adye/parasail/pip-egg-info
         cwd: /tmp/pip-install-85z4adye/parasail/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-85z4adye/parasail/setup.py", line 18, in <module>
        from wheel.bdist_wheel import bdist_wheel as bdist_wheel_
    ImportError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
$ pip install parasail==1.2 --no-cache                                                                                                                                                                        
Collecting parasail==1.2
  Downloading parasail-1.2-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
     |████████████████████████████████| 14.1 MB 3.2 MB/s 
Collecting numpy
  Downloading numpy-1.18.1-cp35-cp35m-manylinux1_x86_64.whl (19.9 MB)
     |████████████████████████████████| 19.9 MB 43.7 MB/s 
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: numpy, wheel, parasail
Successfully installed numpy-1.18.1 parasail-1.2 wheel-0.34.2
```

**Comment by jeffdaily** [comment]
Deployment moved to github actions.
