### ISSUE TITLE
Failed to build parasail>=1.1.12 on M1 Mac

### ISSUE THREAD

**Issue by MasaakiU** [jeffdaily/parasail-python#74]
Hello, `pip install parasail` fails showing the following error:
```
Collecting parasail
  Using cached parasail-1.3.4.tar.gz (83 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages (from parasail) (1.26.2)
Building wheels for collected packages: parasail
  Building wheel for parasail (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      parasail/libparasail.dylib not found, attempting to build
      Downloading latest parasail master
      Unzipping parasail master archive
      fixing executable bits after unzipping
      Unable to find parasail configure script
      Prepending /usr/bin to PATH
      PATH=/usr/bin:/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/bin:/opt/homebrew/Cellar/pyenv/2.2.5/libexec:/opt/homebrew/Cellar/pyenv/2.2.5/plugins/python-build/bin:/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/condabin:/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/masaaki/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
      Running autoreconf -fi from ./parasail-master
      b'This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level'
      b'GNU M4 1.4.6'
      b'autoconf (GNU Autoconf) 2.71'
      automake not found
      glibtoolize not found
      b'autoreconf (GNU Autoconf) 2.71'
      Prepending /private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools/bin to PATH
      PATH=/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools/bin:/usr/bin:/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/bin:/opt/homebrew/Cellar/pyenv/2.2.5/libexec:/opt/homebrew/Cellar/pyenv/2.2.5/plugins/python-build/bin:/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/condabin:/opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/masaaki/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
      Building autotools
      Downloading http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
      Expanding m4-1.4.17.tar.gz
      configuring m4
      running ./configure --prefix=/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools
      making and installing m4
      Downloading http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
      Expanding autoconf-2.69.tar.gz
      configuring autoconf
      running ./configure --prefix=/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools
      making and installing autoconf
      Downloading http://ftp.gnu.org/gnu/automake/automake-1.15.1.tar.gz
      Expanding automake-1.15.1.tar.gz
      configuring automake
      running ./configure --prefix=/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools
      making and installing automake
      Downloading http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz
      Expanding libtool-2.4.6.tar.gz
      configuring libtool
      running ./configure --prefix=/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/autotools
      making and installing libtool
      Running autoreconf -fi from ./parasail-master
      b'This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level'
      m4 --version failed
      b'autoconf (GNU Autoconf) 2.69'
      b'automake (GNU automake) 1.15.1'
      glibtoolize not found
      b'autoreconf (GNU Autoconf) 2.69'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/setup.py", line 515, in <module>
          setup(
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/masaaki/.pyenv/versions/miniforge3-4.10.3-10/envs/env_MultiplexNanopore_2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/setup.py", line 488, in run
          prepare_shared_lib()
        File "/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/setup.py", line 470, in prepare_shared_lib
          build_parasail(libname)
        File "/private/var/folders/hf/_7ybqmjj2f1dlvrdshbsq_sw0000gp/T/pip-install-7ypcnvqw/parasail_b663c8bb2f7b40f9a43327954cddb4de/setup.py", line 340, in build_parasail
          raise RuntimeError("autoreconf -fi failed")
      RuntimeError: autoreconf -fi failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for parasail
  Running setup.py clean for parasail
Failed to build parasail
ERROR: Could not build wheels for parasail, which is required to install pyproject.toml-based projects
```

Could you help me with this problem?
I'm on MacBook Air (2020 model with M1 chip, macOS Ventura 13.0.1) and Python 3.10.13.
Of note, `pip install parasail==1.1.11` went well, but not with newer (>=1.1.12) version.
Thank you for your help in advance.

**Comment by wasimxyz** [comment]
Having a similar issue on my M2 MacBook Pro. Can't install earlier versions either unfortunately.

**Comment by jayhesselberth** [comment]
I went for the nuclear option described in https://github.com/d12frosted/homebrew-emacs-plus/issues/728#issuecomment-2347075236 and successfully built on M3.

Install build tools with homebrew.

```
brew install autoconf automake libtool
```

Then rm and link system m4 and gm4 to the homebrew versions:

```
❯ ls -l /Library/Developer/CommandLineTools/usr/bin/ | grep m4
-rwxr-xr-x 1 root wheel    202992 Dec  7 00:15 bm4*
lrwxr-xr-x 1 root wheel        27 Jan 18 22:06 gm4 -> /opt/homebrew/opt/m4/bin/m4*
lrwxr-xr-x 1 root wheel        27 Jan 18 22:06 m4 -> /opt/homebrew/opt/m4/bin/m4*
```
